<CameraMenuHeader>:
    orientation: "vertical"
    adaptive_size: True
    padding: "5dp"

    MDBoxLayout:
        spacing: "12dp"
        adaptive_size: True

        MDIconButton:
            icon: "gesture-tap-button"
            pos_hint: {"center_y": .5}

        MDLabel:
            text: "Camera Menu"
            font_style: "Inter"
            adaptive_size: True
            pos_hint: {"center_y": .5}