<CalibrateScreenView>:

    FloatLayout:
        size: root.size

        MDFloatingActionButtonSpeedDial:
            id: speed_dial
            data: app.modules
            root_button_anim: True
            hint_animation: True
            bg_color_root_button: "teal"
            bg_color_stack_button: "teal"
            bg_hint_color: "teal"
            label_text_color: "white"
            color_icon_root_button: "white"
            color_icon_stack_button: "white"
